#!/usr/bin/env python
import os
from classes.ptm import Ptm

def main():
    # For the given path, get the full path list of transistors models
    dir_name = '/work_bgfs/i/iliabautista/2-Research/2-Simulations/1-HDL/hspice/modelfiles/'

    temp = Ptm("test", "nfet.pm", "pfet.pm")

    subdir_paths = temp.set_uut_dir(dir_name) # create uut directories and sbudirs

    temp.set_fet_subckts(subdir_paths) # create fet subckt in subdirs

    nfin = 1000

    for path, model_uut in zip(subdir_paths[1:],temp.models_subdir):
        with open(path + "/" + temp.uut + ".sp", 'w+') as uut:
            (fet_size, fet_voltage) = temp.get_fet_params(model_uut)

            uut.write("$This UUT was automatically generated by:\n")
            uut.write("$" + os.getcwd() + "/" + __file__ + "\n\n")

            uut.write("$Netlist of " + temp.uut + "\n")
            uut.write(".include " + model_uut + "\n\n")

            uut.write("$FETs" + "\n")
            uut.write("xpfet" + "1" + " out in vdd vdd pfet l=" + fet_size + "n nfin=" + str(nfin) + "m\n")
            uut.write("xnfet" + "1" + " out in gnd gnd nfet l=" + fet_size + "n nfin=" + str(nfin) + "m\n\n")

            uut.write("$Output Load\n")
            uut.write("c" + "1" + " out 0 5f\n\n")

            uut.write("$Power Sources\n")
            uut.write("vdd vdd gnd " + fet_voltage + "V\n")
            uut.write("vin in  gnd  PULSE(0V " + fet_voltage + "V 0ns 50ps 50ps 1ns 20ns)\n\n")
            
            uut.write(".option post=2\n\n")
            
            uut.write("$Analysis\n")
            uut.write(".tran 10ps 4ns\n\n")

            uut.write(".end")


if __name__ == '__main__':
    main()

